[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-C3)
#target = "xtensa-esp32-espidf"
target = "riscv32imc-esp-espidf"


[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "--cfg",
    "mio_unsupported_force_poll_poll",
    "--cfg",
    "espidf_time64",
    "-C",
    "default-linker-libraries",
]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "--cfg",
    "espidf_time64",
    "--cfg",
    "mio_unsupported_force_poll_poll",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
CRATE_CC_NO_DEFAULTS = "1"
MCU = "esp32c3"
# DANGER! DO NOT UPDATE THIS until esp-idf-svc supports newer versions
# ESP_IDF_VERSION = "v5.3.2"
ESP_IDF_VERSION = "v5.4.2"
